### ISSUE TITLE
Bug Header CL COMEDIE - ARTISTES

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#106]
L'image du header sur les 2 pages artistes ne semblent pas etre a la meme taille quand on passe de la page artistes a venir/ artistes precedemment

**Comment by simple-acces** [comment]
Idem sur la page partenaires après verification!

**Comment by RonanDrouglazet** [comment]
en fait c'est lorsque tu à modifié tes pages, tu as supprimé les éléments à l'intérieur d'un conteneur, au lieu de supprimer directement le container lui même, du coup sur certaine page y'a un container vide qui pousse le content plus bas, et sur d'autre non donc je vais t'enlever ce container vide partout :)
