### ISSUE TITLE
Warning changement de page

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#127]
Quand on quitte une page sur octoboot pour en charger une nouvelle, serait-ce possible de rajouter une alerte avant du style "vous allez changer de page, avez-vous bien enregistré votre travail" Poursuivre/annuler

**Comment by RonanDrouglazet** [comment]
Oui j'y est pensé, et j'ai même la possibilité de sauvegarder automatiquement ton travail en "mémoire" (pas en vrai) et donc quand tu retourne sur une page ou il détecte que t'avais un taf en cours pas save, il te propose de recup le document 

comme word etc... tu vois ?
