### ISSUE TITLE
Publication github

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#148]
A la publication via github j'ai 2 écrans fondus ensemble. L'un me dit publication reussie avec le lien et l'autre publication ongoing avec une roue qui tourne. ce dernier écran ne disparait jamais... Pourtant le site est bien mis à jour

**Comment by RonanDrouglazet** [comment]
ok merci je check

**Comment by RonanDrouglazet** [comment]
je n'arrive pas à reproduire ... on regardera ensemble stp

**Comment by simple-acces** [comment]
ok!

**Comment by simple-acces** [comment]
je garde le screenflow

**Comment by RonanDrouglazet** [comment]
voir douceur en equilibre sur surface
