### ISSUE TITLE
Utilisation generale -Link

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#155]
Question à moi meme...
Si je veux supprimer un lien mais pas le contenu vers lequel renvoyait le lien, c'est possible? (en mettant un lien vide par exemple???)

**Comment by RonanDrouglazet** [comment]
hmm, pas vraiment car ça restera un "lien" donc avec la souris qui ce transforme en main etc...
par contre il faut que je rajoute dans la modification du lien le fait de pouvoir le supprimer 

donc à voir / faire de mon coté

**Comment by simple-acces** [comment]
a ma question a moi meme n'était donc pas inutile!
