### ISSUE TITLE
Edition du texte des valeurs - bloc et titre

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#157]
Je pense avoir compris comment magalie avait supprimé les blocs de texte, j'ai reussi à la faire...Tu edites le bloc d'explication des valeurs puis après tu le fais disparaitre puis tu tentes de modifier le titre. J'ai finalement perdu le bloc... J'ai peut etre mal fait...

**Comment by RonanDrouglazet** [comment]
ok, pas sûr de bien comprendre comment tu as fait il faudra que tu me montre ce soir 
je te les remets
