### ISSUE TITLE
RS - Iberia/PT probleme des boutons fixes sur les fiches produits

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/OctoBoot#178]
Le cas sur excellia anejo

**Comment by simple-acces** [comment]
je sais qu'on en avait parlé et qu'on avait conclu que mettre une position fixe (demandée par l'agence) était une très mauvaise idée je vais donc prevenir magalie screen a l'appui qu'on passe les boutons en relatif

**Comment by RonanDrouglazet** [comment]
me rappel plus si on l'a fait ça du coup, tu t'en rappel @simple-acces ..?
